[platformio]
; src_dir = src/ANCHOR-1A1T ;Anchor for 1 Tag 1 Anchor 
; src_dir = src/ANCHOR-MA1T ;Anchor for multi Tag 1 Anchor 
src_dir = src/TAG-1A1T    ;TAG for 1 Tag 1 Anchor 
; src_dir = src/TAG-MA1T    ;TAG for 1 Tag 1 Anchor 

[env:nodemcu_bu01]
platform = ststm32
board = nodemcu_bu01
framework = arduino
board_build.mcu = stm32f103c8t6
board_build.f_cpu = 72000000L

upload_protocol = stlink
monitor_speed = 115200

lib_deps =
    thotro/DW1000 @ ^0.9.0